### ISSUE TITLE
Look for non-standard bower install locations

### ISSUE THREAD

**Issue by will-ob** [bahmutov/deps-ok#14]
Bower lets you configure its install directory in a `.bowerrc` file. It looks like deps-ok only checks the default location.

    // .bowerrc
    {
       "directory": "vendor/bower",
       "json": "bower.json"
    }

Output:

    ERROR: cannot find folder /home/will/projects/toad/bower_components/backbone

npm worked like a champ though :) looking forward to adding this into our build

**Comment by tilmanpotthof** [comment]
I have the same problem. I try to write a fix within the next days.
