### ISSUE TITLE
Warn and skip git: dependencies

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/deps-ok#17]
Skip with warning dependencies that have git: versions, like `git://github.com/bahmutov/grunt-regex-check.git#33b25690780261f8fa4fa7fc43cff5775bd4cd7c`

**Comment by dolzenko** [comment]
Just wondering - why these are skipped? From looking at `package.json` for package installed from git it seems like there is enough info to check these too (npm added `"_resolved"` and `"_from"` keys)?

**Comment by bahmutov** [comment]
What is the syntax and meaning for _resolved and _from? I skipped the git urls because they are just commit-ish ids

**Comment by dolzenko** [comment]
I think `_resolved` stores SHA of commit for installed package, so if `package.json` points to specific commit it could be checked that both match.

**Comment by bahmutov** [comment]
I will think about this, right now I do not have a need to point at github repos from package.json fortunately.
