### ISSUE TITLE
check version in .bower.json file

### ISSUE THREAD

**Issue by tilmanpotthof** [bahmutov/deps-ok#19]
The version in a bower.json file is ignored and the version "truth" is the git tag. Therefore some bower modules argue not to use and refer to the spec (https://github.com/bower/bower.json-spec#version).

Bower 1.4 puts a `.bower.json` file in an installed component which contains the version number. I haven't checked since which version bower does that, but it's probably the more reliable information.

Related discussion for the module `bootstrap-css-only` https://github.com/fyockm/bootstrap-css-only/pull/7#issuecomment-91580220

**Comment by tilmanpotthof** [comment]
I found a clear statement in the related bower issue **Should Bower tools use `.bower.json` rather than `bower.json`?**: 

> So yeah. The ultimate answer is: use .bower.json.
> If you have any issues with it, please open new issue :)


source: https://github.com/bower/bower/issues/1174

**Comment by bahmutov** [comment]
Merged the pull request, released as 0.10.1
